apiVersion: apps/v1
kind: Deployment
metadata:
  name: itdt-contained-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: itdt-contained-frontend
  template:
    metadata:
      labels:
        app: itdt-contained-frontend
    spec:
      containers:
      - name: itdt-contained-frontend
        image:  ifilyaninitmo/itdt-contained-frontend:master
        env:
          - name: REACT_APP_USERNAME
            value: Veselov Ilya
          - name: REACT_APP_COMPANY_NAME
            value: ITMO
        ports:
        - containerPort: 3000