apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: itdt-contained-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: itdt-contained-frontend
  template:
    metadata:
      labels:
        app: itdt-contained-frontend
    spec:
      containers:
      - name: itdt-contained-frontend
        image:  ifilyaninitmo/itdt-contained-frontend:master
        envFrom:
          - configMapRef:
              name: itdt-frontend
        ports:
        - containerPort: 3000